### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by egarim** [jaystack/odata-v4-server-mongodb-example#12]
Hi I can create the tutorial for you guys i have been able to compile and test the project but not to run it. when i run the npm start command i got this
npm ERR! missing script: start

when I define the start command on the package.json i got this ouput

odata-v4-server-mongodb-example@0.1.0 start C:\jdata
node lib/js/server.js
no error or anything, but when I browse

http://localhost:3000/

there is nothing running there, any idea of what I'm doing wrong? I'm able to see the data on the mongo server and the test works perfect

**Comment by egarim** [comment]
Any update here?

**Comment by kperusko** [comment]
@egarim I ran into the same problem. They're using Docker now, but I guess they forgot to update the documentation.

To get the example working without Docker, I did:
```
npm run build
node .
```

That will start the server on localhost:3000

**Comment by lazarv** [comment]
@egarim and @kperusko the npm start script is now available. Doing the same thing @kperusko wrote.
